name: barcode-merge
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - scipy
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statannotations
  - statsmodels
  - biopython